(() => {
  let templates = [], preview = null;
  const style = document.createElement('style');
  style.textContent = `
    .template-btn{white-space:nowrap}.plan-modal{position:fixed;inset:0;z-index:30;display:none;place-items:center;padding:16px;background:rgba(17,25,42,.48)}.plan-modal.show{display:grid}.plan-box{width:min(760px,100%);max-height:min(86vh,820px);overflow:auto;padding:24px;background:#fff;border-radius:18px;box-shadow:0 25px 80px rgba(0,0,0,.2)}.plan-box h2{margin:0}.plan-note{margin:8px 0 18px;color:#697586;font-size:13px;line-height:1.6}.plan-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.plan-field{display:grid;gap:6px;font-size:13px;color:#475569}.plan-field.wide{grid-column:1/-1}.template-details,.plan-preview{margin-top:16px;padding:14px;border:1px solid #dfe5f3;border-radius:12px;background:#f8faff}.template-details h3,.plan-preview h3{margin:0 0 8px;font-size:15px}.template-details p{margin:0;color:#59677d;font-size:13px;line-height:1.6}.consumables{margin:10px 0 0;padding-left:18px;color:#59677d;font-size:13px}.plan-steps{display:grid;gap:8px;margin-top:10px}.plan-step{padding:10px;border-radius:9px;background:#fff;border-left:3px solid #5879de;font-size:13px;line-height:1.55}.plan-step small{display:block;color:#697586;margin-top:3px}.plan-step .deps{color:#8a5d08}.plan-conflicts{margin-top:10px;padding:10px;border-radius:9px;background:#fff1f1;color:#a42934;font-size:13px;line-height:1.55}.plan-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}@media(max-width:640px){.plan-fields{grid-template-columns:1fr}.plan-field.wide{grid-column:auto}.plan-box{padding:18px}}
  `;
  document.head.appendChild(style);

  const modal = document.createElement('div');
  modal.className = 'plan-modal';
  modal.innerHTML = `<section class="plan-box"><h2>模板与依赖规划</h2><p class="plan-note">选择模板后先预览步骤、依赖和仪器冲突；确认无误才会批量写入实验日历。模板仅用于计划管理，具体操作请遵循实验室 SOP。</p><div class="plan-fields"><label class="plan-field wide">实验模板<select id="template-select"></select></label><label class="plan-field">计划名称（可选）<input id="plan-name" placeholder="例如：8 月 CCK-8 药物筛选"></label><label class="plan-field">计划开始时间<input id="plan-start" type="datetime-local" required></label></div><div class="template-details" id="template-details"></div><div class="plan-preview" id="plan-preview" style="display:none"></div><div class="plan-actions"><button class="btn" type="button" id="plan-close">取消</button><button class="btn" type="button" id="plan-preview-btn">预览计划</button><button class="btn primary" type="button" id="plan-create-btn" disabled>确认写入日历</button></div></section>`;
  document.body.appendChild(modal);
  const select = modal.querySelector('#template-select'), details = modal.querySelector('#template-details'), previewBox = modal.querySelector('#plan-preview'), startInput = modal.querySelector('#plan-start'), nameInput = modal.querySelector('#plan-name'), previewButton = modal.querySelector('#plan-preview-btn'), createButton = modal.querySelector('#plan-create-btn');

  function defaultLocalTime() { const date = new Date(); date.setMinutes(0, 0, 0); date.setHours(date.getHours() + 1); const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 16); }
  function currentTemplate() { return templates.find(item => item.id === select.value); }
  function showTemplate() { const template = currentTemplate(); preview = null; previewBox.style.display = 'none'; createButton.disabled = true; if (!template) return; details.innerHTML = `<h3>${escapeHtml(template.name)}</h3><p>${escapeHtml(template.description)}</p><ul class="consumables"><li><b>预计步骤：</b>${template.steps.length} 项</li><li><b>建议准备：</b>${template.consumables.map(escapeHtml).join('、')}</li></ul>`; }
  function stepHtml(step) { const deps = step.depends_on?.length ? `依赖步骤：${step.depends_on.map(index => `#${index}`).join('、')}` : '起始步骤'; const start = new Date(step.start_at).toLocaleString('zh-CN', {month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}); const end = new Date(step.end_at).toLocaleTimeString('zh-CN', {hour:'2-digit',minute:'2-digit'}); return `<article class="plan-step"><b>#${step.order} ${escapeHtml(step.short_name)}</b><small>${start} — ${end}${step.equipment ? ` · ${escapeHtml(step.equipment)}` : ''}</small><small class="deps">${deps}</small></article>`; }
  function showPreview(data) { const conflictHtml = data.conflicts?.length ? `<div class="plan-conflicts"><b>检测到冲突，当前不能写入：</b><br>${data.conflicts.map(item => `步骤 #${item.order}「${escapeHtml(item.name)}」与已有实验冲突`).join('<br>')}</div>` : `<p class="plan-note" style="margin:10px 0 0;color:#08745a">未发现已有仪器时间冲突，可以确认写入日历。</p>`; previewBox.innerHTML = `<h3>${escapeHtml(data.plan_name)} · 共 ${data.steps.length} 个依赖步骤</h3><div class="plan-steps">${data.steps.map(stepHtml).join('')}</div>${conflictHtml}`; previewBox.style.display = 'block'; createButton.disabled = !data.ready; }
  async function request(url) { const body = {template_id: select.value, start_at: startInput.value, name: nameInput.value.trim()}; const response = await fetch(url, {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); const data = await response.json(); if (!response.ok) throw new Error(data.detail?.message || data.detail || '请求失败'); return data; }
  async function openPlanner() { modal.classList.add('show'); startInput.value = defaultLocalTime(); if (templates.length) return; try { const response = await fetch('/experiment-templates'); if (!response.ok) throw new Error('无法读取实验模板'); templates = await response.json(); select.innerHTML = templates.map(item => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)}</option>`).join(''); showTemplate(); } catch (error) { notify(error.message); modal.classList.remove('show'); } }
  select.onchange = showTemplate;
  previewButton.onclick = async () => { if (!startInput.value) return notify('请先选择计划开始时间'); previewButton.disabled = true; try { preview = await request('/experiment-templates/preview'); showPreview(preview); } catch (error) { notify(error.message); } finally { previewButton.disabled = false; } };
  createButton.onclick = async () => { if (!preview?.ready) return; if (!confirm(`确认将 ${preview.steps.length} 个步骤写入实验日历吗？`)) return; createButton.disabled = true; try { const result = await request('/experiment-templates/plans'); notify(`已创建 ${result.steps.length} 个计划步骤`); modal.classList.remove('show'); await loadExperiments(); viewDate = parseDate(result.start_at) || viewDate; renderCalendar(); } catch (error) { notify(error.message); } finally { createButton.disabled = false; } };
  modal.querySelector('#plan-close').onclick = () => modal.classList.remove('show'); modal.onclick = event => { if (event.target === modal) modal.classList.remove('show'); };
  const actionArea = document.querySelector('.calendar-card .buttons');
  if (actionArea) { const button = document.createElement('button'); button.type = 'button'; button.className = 'btn template-btn'; button.textContent = '模板规划'; button.onclick = openPlanner; actionArea.appendChild(button); }
  window.openTemplatePlanner = openPlanner;
})();
