(() => {
  const conversationKey = 'lab-agent-conversation-id';
  const labels = { queued: '排队中', running: '处理中', cancelling: '取消中', cancelled: '已取消', completed: '已完成', failed: '失败' };
  const active = new Set(['queued', 'running', 'cancelling']);
  const style = document.createElement('style');
  style.textContent = `.task-card{padding:20px}.task-list{margin-top:13px;display:grid;gap:10px}.task-item{padding:11px;border:1px solid #e3e8f3;border-radius:10px;background:#fbfcff}.task-title{display:flex;justify-content:space-between;gap:8px;font-weight:700;font-size:13px}.task-status{white-space:nowrap;padding:2px 7px;border-radius:12px;background:#edf1ff;color:#405ec4;font-size:11px}.task-status.completed{background:#e4f6ee;color:#08745a}.task-status.failed,.task-status.cancelled{background:#fff0f0;color:#b5303c}.task-meta{margin-top:5px;color:#697586;font-size:12px;line-height:1.5}.task-cancel{margin-top:7px;padding:4px 8px;border:1px solid #f1c0c5;border-radius:7px;background:#fff;color:#b5303c;font-size:12px;cursor:pointer}.task-empty{padding:20px 0;color:#697586;font-size:13px;text-align:center}`;
  document.head.appendChild(style);
  const card = document.createElement('section'); card.className = 'card task-card'; card.id = 'task-card'; card.innerHTML = '<div class="card-head"><div><h2>后台任务</h2><p class="sub">任务会在后台继续执行</p></div><button class="btn" type="button" id="task-refresh">刷新</button></div><div class="task-list" id="task-list"><p class="task-empty">暂无后台任务。</p></div>';
  document.querySelector('.right')?.appendChild(card);
  const list = card.querySelector('#task-list');
  const conversationId = () => localStorage.getItem(conversationKey);
  function render(tasks) { if (!tasks.length) { list.innerHTML = '<p class="task-empty">暂无后台任务。</p>'; return; } list.innerHTML = tasks.map(task => `<article class="task-item"><div class="task-title"><span>${escapeHtml(task.prompt)}</span><span class="task-status ${task.status}">${labels[task.status] || task.status}</span></div><div class="task-meta">${escapeHtml(task.progress || '')}</div>${active.has(task.status) ? `<button class="task-cancel" data-task-id="${task.id}">取消任务</button>` : ''}</article>`).join(''); list.querySelectorAll('.task-cancel').forEach(button => button.onclick = () => cancel(button.dataset.taskId)); }
  async function refresh() { const id = conversationId(); if (!id) return render([]); try { const response = await fetch(`/tasks?conversation_id=${encodeURIComponent(id)}`); if (!response.ok) throw new Error('读取任务失败'); render(await response.json()); } catch (_) { /* 网络异常时保留当前内容 */ } }
  async function cancel(taskId) { try { const response = await fetch(`/tasks/${taskId}/cancel`, {method:'POST'}); if (!response.ok) throw new Error('取消失败'); notify('已请求取消后台任务'); refresh(); } catch (error) { notify(error.message); } }
  async function deliverResults() { const id = conversationId(); if (!id || window.isAssistantBusy?.() || document.querySelector('.mic.listening')) return; try { const response = await fetch(`/tasks/updates?conversation_id=${encodeURIComponent(id)}`); if (!response.ok) return; const updates = await response.json(); for (const task of updates) { const text = task.status === 'completed' ? `后台任务 #${task.id} 已完成：\n${task.result}` : `后台任务 #${task.id} 执行失败：${task.error}`; window.addChatMessage?.(text, 'assistant'); if (document.querySelector('#auto-speak')?.checked) window.enqueueSpeech?.(text); window.dispatchAvatarState?.(task.status === 'completed' ? 'happy' : 'interrupted'); } if (updates.length) { refresh(); setTimeout(() => window.dispatchAvatarState?.('idle'), 1000); } } catch (_) { /* 下次轮询会重试 */ } }
  card.querySelector('#task-refresh').onclick = refresh; window.refreshTaskPanel = refresh; refresh(); setInterval(() => { refresh(); deliverResults(); }, 2000);
})();
