# -*- coding: utf-8 -*-
"""HTTP adapter for the shared experiment-record application service."""

from __future__ import annotations

import json
import uuid

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from playback_runtime import web_playback_service
from record_service import (
    RecordModeConflictError,
    RecordPersistenceError,
)
from database.lab_record_store import (
    current_session_id,
    list_records,
    start_new_session,
)
from mode_snapshot import ModeSnapshotFields
from src.core.conversation_turn import ExperimentContext, InputSource, InteractionMode
from src.core.turn_input import TurnInput
from database.turn_store import TurnRequestConflictError
from output_policy import select_output_policy
from src.core.reply_coordinator import ReplyCoordinator
import domain

router = APIRouter(prefix="/record", tags=["实验记录"])

class RecordPayload(ModeSnapshotFields):
    interaction_mode: InteractionMode = InteractionMode.EXPERIMENT
    experiment_context: ExperimentContext = ExperimentContext.FREE
    transcript: str
    extract: bool = True
    conversation_id: str | None = None


def _submitted_experiment_context(payload: RecordPayload):
    """Legacy internal callers had no mode field; new browser requests always do."""

    return (
        payload.experiment_context
        if "experiment_context" in payload.model_fields_set
        else None
    )


@router.post("")
def record(payload: RecordPayload):
    """处理一段口述，返回结构化结果与确定性追问。"""
    text = (payload.transcript or "").strip()
    policy = select_output_policy(
        payload.interaction_mode, payload.experiment_context
    )
    if not policy.save_observation:
        raise HTTPException(status_code=409, detail="自由聊天模式禁止写入实验记录。")
    if not text:
        raise HTTPException(status_code=400, detail="口述内容为空")
    try:
        return _record_response(
            text, extract=payload.extract, conversation_id=payload.conversation_id,
            experiment_context=_submitted_experiment_context(payload),
            turn_id=payload.turn_id,
            request_id=payload.request_id,
        )
    except RecordModeConflictError as error:
        raise HTTPException(status_code=409, detail=str(error)) from error
    except TurnRequestConflictError as error:
        raise HTTPException(status_code=409, detail=str(error)) from error
    except RecordPersistenceError as error:
        raise HTTPException(status_code=500, detail=str(error)) from error


def _record_response(
    text: str, *, extract: bool, conversation_id: str | None = None,
    experiment_context=None, turn_id: str | None = None,
    request_id: str | None = None,
) -> dict[str, object]:
    """Compatibility response generated by the unified Turn service."""

    from api.turn import turn_application_service

    resolved_conversation = conversation_id or str(uuid.uuid4())
    resolved_request_id = request_id or f"legacy-record-{uuid.uuid4().hex}"
    resolved_turn_id = turn_id or f"turn-{resolved_request_id}"
    context = experiment_context or ExperimentContext.FREE
    session_id = current_session_id()
    turn = TurnInput(
        resolved_conversation, resolved_request_id, resolved_turn_id, session_id,
        InteractionMode.EXPERIMENT, context, 1,
        InputSource.TEXT, text.strip(), None,
    )
    completed = turn_application_service.submit(turn).future.result()
    saved_record = turn_application_service.store.load_lab_record(
        resolved_request_id
    )
    wire_turn = completed.result.get("turn", {})
    record_block = next(
        (block for block in wire_turn.get("blocks", [])
         if block.get("type") == "record_card"),
        None,
    )
    assistant_block = next(
        (block for block in wire_turn.get("blocks", [])
         if block.get("type") == "assistant_text"),
        None,
    )
    business = dict(completed.result.get("business", {}))
    voice_item = completed.voice_items[0] if completed.voice_items else None
    response = {
        "session_id": session_id,
        "segment_id": business.get("segment_id"),
        "transcript": text.strip(),
        "entities": (record_block or {}).get("payload", {}).get("entities", {}),
        "messages": ([{
            "intent_id": getattr(voice_item, "intent_id", f"{resolved_turn_id}:message"),
            "kind": getattr(getattr(voice_item, "kind", None), "value", "assistant_reply"),
            "priority": getattr(getattr(voice_item, "priority", None), "name", "REVIEW"),
            "screen_target": "dialogue",
            "text": (assistant_block or {}).get("payload", {}).get("text", "处理完成。"),
        }] if assistant_block is not None else []),
        "voice_delivery_events": [],
        "turn": wire_turn,
        "business": business,
        "timing": completed.result.get("timing", {}),
    }
    if saved_record is not None:
        response.update({
            key: value for key, value in saved_record.items()
            if key not in {"id", "created_at", "request_id", "conversation_id", "turn_id"}
        })
    if not completed.replayed and completed.voice_items:
        response["voice_delivery_events"] = list(
            web_playback_service.authorize(
                completed.voice_items, conversation_id=resolved_conversation
            )
        )
    return response


def _stream_event(payload: dict[str, object]) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"


def _record_events(
    text: str, *, extract: bool, conversation_id: str | None = None,
    experiment_context=None, turn_id: str | None = None,
    request_id: str | None = None,
):
    """Yield immediate progress, then the same committed result as POST /record."""

    yield _stream_event({
        "type": "record_status",
        "phase": "understanding",
        "text": "正在理解实验内容…",
    })
    try:
        response = _record_response(
            text, extract=extract, conversation_id=conversation_id,
            experiment_context=experiment_context,
            turn_id=turn_id,
            request_id=request_id,
        )
    except (
        RecordPersistenceError,
        RecordModeConflictError,
        TurnRequestConflictError,
    ) as error:
        yield _stream_event({"type": "record_error", "detail": str(error)})
        return
    except Exception as error:
        yield _stream_event({
            "type": "record_error",
            "detail": f"处理失败：{type(error).__name__}: {error}",
        })
        return
    yield _stream_event({"type": "record_result", "data": response})


@router.post("/stream")
def record_stream(payload: RecordPayload):
    """Stream progress while preserving the post-commit result boundary."""

    text = (payload.transcript or "").strip()
    policy = select_output_policy(
        payload.interaction_mode, payload.experiment_context
    )
    if not policy.save_observation:
        raise HTTPException(status_code=409, detail="自由聊天模式禁止写入实验记录。")
    if not text:
        raise HTTPException(status_code=400, detail="口述内容为空")
    return StreamingResponse(
        _record_events(
            text, extract=payload.extract, conversation_id=payload.conversation_id
            , experiment_context=_submitted_experiment_context(payload),
            turn_id=payload.turn_id,
            request_id=payload.request_id,
        ),
        media_type="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )



@router.get("/history")
def history(
    conversation_id: str | None = None,
    lab_session_id: str | None = None,
):
    """读取实验账本；无联合身份时保留旧版全局会话兼容响应。"""
    if conversation_id is not None or lab_session_id is not None:
        if not conversation_id or not lab_session_id:
            raise HTTPException(
                status_code=400,
                detail="conversation_id 和 lab_session_id 必须同时提供。",
            )
        from api.turn import turn_store

        ledger = turn_store.load_experiment_ledger(
            conversation_id, lab_session_id
        )
        coordinator = ReplyCoordinator.from_snapshot(
            dict(ledger["reply_coordinator"])
        )
        clarification_answers = ledger.get("clarification_answers") or {}
        clarifications = [{
            "clarification_id": item.clarification_id,
            "display_number": item.display_number,
            "question": item.question,
            "missing_fields": list(item.missing_fields),
            "status": item.status.value,
            "protocol_step_number": item.protocol_step_number,
            "answers": clarification_answers.get(item.clarification_id, []),
        } for item in coordinator.all_clarifications()]
        protocol_execution = ledger["protocol_execution"]
        projected_records = [
            domain.project_record_evaluation(dict(item))
            for item in ledger["records"]
        ]
        return {
            "source": "unified_turn",
            "conversation_id": conversation_id,
            "session_id": lab_session_id,
            "revision": ledger["revision"],
            "count": len(projected_records),
            "items": projected_records,
            "clarifications": clarifications,
            "protocol": {
                "protocol_id": protocol_execution.get("protocol_id"),
                "protocol_version": protocol_execution.get("protocol_version"),
                "current_step_number": protocol_execution.get(
                    "current_step_number"
                ),
                "step_statuses": protocol_execution.get("statuses") or {},
                "steps": protocol_execution.get("steps") or {},
            } if protocol_execution else None,
        }

    session_id = current_session_id()
    items = list_records(session_id)
    return {
        "source": "legacy_record",
        "session_id": session_id,
        "count": len(items),
        "items": items,
        "clarifications": [],
        "protocol": None,
    }


@router.post("/reset")
def reset():
    """开始新会话。"""
    session_id = start_new_session()
    return {"session_id": session_id, "message": "已开始新会话"}
