# -*- coding: utf-8 -*-
"""HTTP adapter for the shared experiment-record application service."""

from __future__ import annotations

import json
import uuid

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from playback_runtime import web_playback_service
from record_service import (
    RecordModeConflictError,
    RecordPersistenceError,
)
from database.lab_record_store import (
    current_session_id,
    list_records,
    start_new_session,
)
from mode_snapshot import ModeSnapshotFields
from src.core.conversation_turn import ExperimentContext, InputSource, InteractionMode
from src.core.turn_input import TurnInput
from database.turn_store import TurnRequestConflictError
from output_policy import select_output_policy
from src.core.reply_coordinator import ReplyCoordinator
import domain

router = APIRouter(prefix="/record", tags=["实验记录"])

class RecordPayload(ModeSnapshotFields):
    interaction_mode: InteractionMode = InteractionMode.EXPERIMENT
    experiment_context: ExperimentContext = ExperimentContext.FREE
    transcript: str
    extract: bool = True
    conversation_id: str | None = None


def _submitted_experiment_context(payload: RecordPayload):
    """Legacy internal callers had no mode field; new browser requests always do."""

    return (
        payload.experiment_context
        if "experiment_context" in payload.model_fields_set
        else None
    )


@router.post("")
def record(payload: RecordPayload):
    """处理一段口述，返回结构化结果与确定性追问。"""
    text = (payload.transcript or "").strip()
    policy = select_output_policy(
        payload.interaction_mode, payload.experiment_context
    )
    if not policy.save_observation:
        raise HTTPException(status_code=409, detail="自由聊天模式禁止写入实验记录。")
    if not text:
        raise HTTPException(status_code=400, detail="口述内容为空")
    try:
        return _record_response(
            text, extract=payload.extract, conversation_id=payload.conversation_id,
            experiment_context=_submitted_experiment_context(payload),
            turn_id=payload.turn_id,
            request_id=payload.request_id,
        )
    except RecordModeConflictError as error:
        raise HTTPException(status_code=409, detail=str(error)) from error
    except TurnRequestConflictError as error:
        raise HTTPException(status_code=409, detail=str(error)) from error
    except RecordPersistenceError as error:
        raise HTTPException(status_code=500, detail=str(error)) from error


def _record_response(
    text: str, *, extract: bool, conversation_id: str | None = None,
    experiment_context=None, turn_id: str | None = None,
    request_id: str | None = None,
) -> dict[str, object]:
    """Compatibility response generated by the unified Turn service."""

    from api.turn import turn_application_service

    resolved_conversation = conversation_id or str(uuid.uuid4())
    resolved_request_id = request_id or f"legacy-record-{uuid.uuid4().hex}"
    resolved_turn_id = turn_id or f"turn-{resolved_request_id}"
    context = experiment_context or ExperimentContext.FREE
    session_id = current_session_id()
    turn = TurnInput(
        resolved_conversation, resolved_request_id, resolved_turn_id, session_id,
        InteractionMode.EXPERIMENT, context, 1,
        InputSource.TEXT, text.strip(), None,
    )
    completed = turn_application_service.submit(turn).future.result()
    saved_record = turn_application_service.store.load_lab_record(
        resolved_request_id
    )
    wire_turn = completed.result.get("turn", {})
    record_block = next(
        (block for block in wire_turn.get("blocks", [])
         if block.get("type") == "record_card"),
        None,
    )
    assistant_block = next(
        (block for block in wire_turn.get("blocks", [])
         if block.get("type") == "assistant_text"),
        None,
    )
    business = dict(completed.result.get("business", {}))
    voice_item = completed.voice_items[0] if completed.voice_items else None
    response = {
        "session_id": session_id,
        "segment_id": business.get("segment_id"),
        "transcript": text.strip(),
        "entities": (record_block or {}).get("payload", {}).get("entities", {}),
        "messages": ([{
            "intent_id": getattr(voice_item, "intent_id", f"{resolved_turn_id}:message"),
            "kind": getattr(getattr(voice_item, "kind", None), "value", "assistant_reply"),
            "priority": getattr(getattr(voice_item, "priority", None), "name", "REVIEW"),
            "screen_target": "dialogue",
            "text": (assistant_block or {}).get("payload", {}).get("text", "未生成回复，请重试。"),
        }] if assistant_block is not None else []),
        "voice_delivery_events": [],
        "turn": wire_turn,
        "business": business,
        "timing": completed.result.get("timing", {}),
    }
    if saved_record is not None:
        response.update({
            key: value for key, value in saved_record.items()
            if key not in {"id", "created_at", "request_id", "conversation_id", "turn_id"}
        })
    if not completed.replayed and completed.voice_items:
        response["voice_delivery_events"] = list(
            web_playback_service.authorize(
                completed.voice_items, conversation_id=resolved_conversation
            )
        )
    return response


def _stream_event(payload: dict[str, object]) -> str:
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n"


def _record_events(
    text: str, *, extract: bool, conversation_id: str | None = None,
    experiment_context=None, turn_id: str | None = None,
    request_id: str | None = None,
):
    """Yield immediate progress, then the same committed result as POST /record."""

    yield _stream_event({
        "type": "record_status",
        "phase": "understanding",
        "text": "正在理解实验内容…",
    })
    try:
        response = _record_response(
            text, extract=extract, conversation_id=conversation_id,
            experiment_context=experiment_context,
            turn_id=turn_id,
            request_id=request_id,
        )
    except (
        RecordPersistenceError,
        RecordModeConflictError,
        TurnRequestConflictError,
    ) as error:
        yield _stream_event({"type": "record_error", "detail": str(error)})
        return
    except Exception as error:
        yield _stream_event({
            "type": "record_error",
            "detail": f"处理失败：{type(error).__name__}: {error}",
        })
        return
    yield _stream_event({"type": "record_result", "data": response})


@router.post("/stream")
def record_stream(payload: RecordPayload):
    """Stream progress while preserving the post-commit result boundary."""

    text = (payload.transcript or "").strip()
    policy = select_output_policy(
        payload.interaction_mode, payload.experiment_context
    )
    if not policy.save_observation:
        raise HTTPException(status_code=409, detail="自由聊天模式禁止写入实验记录。")
    if not text:
        raise HTTPException(status_code=400, detail="口述内容为空")
    return StreamingResponse(
        _record_events(
            text, extract=payload.extract, conversation_id=payload.conversation_id
            , experiment_context=_submitted_experiment_context(payload),
            turn_id=payload.turn_id,
            request_id=payload.request_id,
        ),
        media_type="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )



@router.get("/history")
def history(
    conversation_id: str | None = None,
    lab_session_id: str | None = None,
):
    """读取实验账本；无联合身份时保留旧版全局会话兼容响应。"""
    if conversation_id is not None or lab_session_id is not None:
        if not conversation_id or not lab_session_id:
            raise HTTPException(
                status_code=400,
                detail="conversation_id 和 lab_session_id 必须同时提供。",
            )
        from api.turn import turn_store

        ledger = turn_store.load_experiment_ledger(
            conversation_id, lab_session_id
        )
        coordinator = ReplyCoordinator.from_snapshot(
            dict(ledger["reply_coordinator"])
        )
        clarification_answers = ledger.get("clarification_answers") or {}
        clarifications = [{
            "clarification_id": item.clarification_id,
            "display_number": item.display_number,
            "question": item.question,
            "missing_fields": list(item.missing_fields),
            "status": item.status.value,
            "protocol_step_number": item.protocol_step_number,
            "answers": clarification_answers.get(item.clarification_id, []),
        } for item in coordinator.all_clarifications()]
        protocol_execution = ledger["protocol_execution"]
        projected_records = [
            domain.project_record_evaluation(dict(item))
            for item in ledger["records"]
        ]
        return {
            "source": "unified_turn",
            "conversation_id": conversation_id,
            "session_id": lab_session_id,
            "revision": ledger["revision"],
            "count": len(projected_records),
            "items": projected_records,
            "clarifications": clarifications,
            "protocol": {
                "protocol_id": protocol_execution.get("protocol_id"),
                "protocol_version": protocol_execution.get("protocol_version"),
                "current_step_number": protocol_execution.get(
                    "current_step_number"
                ),
                "step_statuses": protocol_execution.get("statuses") or {},
                "steps": protocol_execution.get("steps") or {},
            } if protocol_execution else None,
        }

    session_id = current_session_id()
    items = list_records(session_id)
    return {
        "source": "legacy_record",
        "session_id": session_id,
        "count": len(items),
        "items": items,
        "clarifications": [],
        "protocol": None,
    }


@router.post("/reset")
def reset():
    """开始新会话。"""
    session_id = start_new_session()
    return {"session_id": session_id, "message": "已开始新会话"}


@router.get("/events")
def record_events():
    """SSE 端点：实验记录一写入就推给前端，不用等轮询。

    前端连接后，每当 save_record 写入新记录，这里会 yield 一条
    ``data: {"type":"record_written",...}`` 事件。前端收到后刷新实验本。
    """
    import time

    from database.lab_record_store import (
        subscribe_record_events,
        unsubscribe_record_events,
    )

    q = subscribe_record_events()

    def event_stream():
        try:
            # 先发一条 hello，让前端确认连接成功。
            yield 'event: hello\ndata: {"type":"connected"}\n\n'
            while True:
                try:
                    event = q.get(timeout=15)
                    payload = json.dumps(event, ensure_ascii=False)
                    yield f'data: {payload}\n\n'
                except Exception:
                    # 15 秒没事件也要发 keepalive，防止代理超时断开。
                    yield ': keepalive\n\n'
        finally:
            unsubscribe_record_events(q)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.get("/sessions")
def list_lab_sessions():
    """实验本首页：列出所有有记录的实验会话，按最近活动排序。

    每个会话包含：方案名、步骤进度、记录条数、首末时间、部分最新记录摘要。
    这是「实验本」页面的数据源——不再用 /experiments（那是实验安排表）。
    """
    import sqlite3
    from database.db import get_connection

    with get_connection() as conn:
        # 所有有记录的会话
        rows = conn.execute(
            """SELECT session_id,
                      COUNT(*) AS record_count,
                      MIN(at) AS first_at,
                      MAX(at) AS last_at,
                      GROUP_CONCAT(DISTINCT conversation_id) AS conv_ids
               FROM lab_records
               GROUP BY session_id
               ORDER BY MAX(id) DESC
               LIMIT 50"""
        ).fetchall()

        # 每个会话的方案信息
        state_rows = conn.execute(
            """SELECT lab_session_id,
                      protocol_step_facts_json,
                      revision,
                      updated_at
               FROM experiment_session_state"""
        ).fetchall()
        protocol_map: dict[str, dict] = {}
        for sr in state_rows:
            facts = json.loads(sr["protocol_step_facts_json"] or "{}")
            protocol_map[sr["lab_session_id"]] = {
                "protocol_id": facts.get("protocol_id"),
                "protocol_version": facts.get("protocol_version"),
                "current_step_number": facts.get("current_step_number"),
                "total_steps": len(facts.get("steps") or {}),
                "revision": sr["revision"],
            }

        # 协议标题
        import domain as domain_module
        proto_titles: dict[str, str] = {}
        try:
            for p in domain_module.protocols().list_all():
                proto_titles[p.protocol_id] = p.title
        except Exception:
            pass

    sessions = []
    for row in rows:
        sid = row["session_id"]
        proto = protocol_map.get(sid, {})
        proto_id = proto.get("protocol_id")
        sessions.append({
            "session_id": sid,
            "conversation_ids": (row["conv_ids"] or "").split(",") if row["conv_ids"] else [],
            "record_count": row["record_count"],
            "first_at": row["first_at"],
            "last_at": row["last_at"],
            "protocol_id": proto_id,
            "protocol_title": proto_titles.get(proto_id, "") if proto_id else "",
            "current_step_number": proto.get("current_step_number"),
            "total_steps": proto.get("total_steps"),
        })
    return {"sessions": sessions}


@router.get("/sessions/{session_id}")
def get_lab_session_detail(session_id: str, conversation_id: str | None = None):
    """实验本详情页：一个实验会话的完整记录。

    返回该会话的所有 lab_records（含 transcript/entities/evaluation/step）
    以及方案步骤进度。
    """
    import sqlite3
    from database.db import get_connection

    with get_connection() as conn:
        rows = conn.execute(
            """SELECT * FROM lab_records
               WHERE session_id = ?
               ORDER BY segment_id, id""",
            (session_id,),
        ).fetchall()

        if not rows:
            raise HTTPException(404, "未找到该实验会话的记录。")

        # 方案状态
        state_row = None
        if conversation_id:
            state_row = conn.execute(
                """SELECT protocol_step_facts_json FROM experiment_session_state
                   WHERE lab_session_id = ? AND conversation_id = ?
                   ORDER BY revision DESC LIMIT 1""",
                (session_id, conversation_id),
            ).fetchone()
        if not state_row:
            state_row = conn.execute(
                """SELECT protocol_step_facts_json FROM experiment_session_state
                   WHERE lab_session_id = ?
                   ORDER BY revision DESC LIMIT 1""",
                (session_id,),
            ).fetchone()

    facts = {}
    if state_row:
        facts = json.loads(state_row["protocol_step_facts_json"] or "{}")

    records = []
    for row in rows:
        item = dict(row)
        for field in ("entities", "extraction", "evaluation", "step"):
            if item.get(field) is not None:
                item[field] = json.loads(item[field])
        records.append(item)

    proto_id = facts.get("protocol_id")
    proto_title = ""
    if proto_id:
        try:
            import domain as domain_module
            proto = domain_module.protocols().get(proto_id)
            proto_title = getattr(proto, "title", "")
        except Exception:
            pass

    return {
        "session_id": session_id,
        "protocol_id": proto_id,
        "protocol_title": proto_title,
        "current_step_number": facts.get("current_step_number"),
        "steps": facts.get("steps") or {},
        "record_count": len(records),
        "records": records,
    }
